feat: dynamic folder creation for artifact shard folders

diff --git a/mutation-testing/check-packages-and-shards/action.yml b/mutation-testing/check-packages-and-shards/action.yml
--- a/mutation-testing/check-packages-and-shards/action.yml
+++ b/mutation-testing/check-packages-and-shards/action.yml
@@ -23,21 +23,25 @@ runs:
 
   steps:
     - name: Checkout stacks-core repo
+      id: checkout_stacks_core
       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
       with:
         fetch-depth: 0
 
     - uses: taiki-e/install-action@ac89944b5b150d78567ab6c02badfbe48b0b55aa # v2.20.16
+      id: install_cargo_mutants
       name: Install cargo-mutants
       with:
         tool: cargo-mutants@23.12.2 # v23.12.2
 
     - name: Relative diff
+      id: relative_diff
       shell: bash
       run: |
         git diff origin/${{ github.base_ref }}.. > git.diff
 
     - name: Update git diff
+      id: update_git_diff
       shell: bash
       run: |
         input_file="git.diff"
@@ -50,7 +54,7 @@ runs:
 
         # Check that the file exists before performing actions on it
         if [ ! -s "$input_file" ]; then
-          echo "Diff file missing!"
+          echo "Diff file (git.diff) is missing or empty!"
           exit 1
         fi
 
@@ -70,19 +74,19 @@ runs:
         # Check that the file exists before performing actions on it
         if [ -s "$temp_file" ]; then
           mv "$temp_file" "$input_file"
-        else
-          echo "Temp diff file missing!"
-          exit 1
+          exit 0
         fi
 
-        exit 0
+        echo "Temp diff file (temp_diff_file.diff) is missing or empty!"
+        exit 1
 
     - name: Split diffs
+      id: split_diffs_by_packages
       shell: bash
       run: |
         # Check that the file exists before performing actions on it
         if [ ! -s git.diff ]; then
-          echo "Diff file missing!"
+          echo "Diff file (git.diff) is missing or empty!"
           exit 1
         fi
 
@@ -92,7 +96,7 @@ runs:
 
         # Check that the file exists before performing actions on it
         if [ ! -s all_mutants.txt ]; then
-          echo "The file containing mutants is missing or empty!"
+          echo "The file containing mutants (all_mutants.txt) is missing or empty!"
           exit 1
         fi
 
